//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

#nullable enable

using System.Text.Json;

#pragma warning disable 108 // Disable "CS0108 '{derivedDto}.ToJson()' hides inherited member '{dtoBase}.ToJson()'. Use the new keyword if hiding was intended."
#pragma warning disable 114 // Disable "CS0114 '{derivedDto}.RaisePropertyChanged(String)' hides inherited member 'dtoBase.RaisePropertyChanged(String)'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword."
#pragma warning disable 472 // Disable "CS0472 The result of the expression is always 'false' since a value of type 'Int32' is never equal to 'null' of type 'Int32?'
#pragma warning disable 612 // Disable "CS0612 '...' is obsolete"
#pragma warning disable 1573 // Disable "CS1573 Parameter '...' has no matching param tag in the XML comment for ...
#pragma warning disable 1591 // Disable "CS1591 Missing XML comment for publicly visible type or member ..."
#pragma warning disable 8073 // Disable "CS8073 The result of the expression is always 'false' since a value of type 'T' is never equal to 'null' of type 'T?'"
#pragma warning disable 3016 // Disable "CS3016 Arrays as attribute arguments is not CLS-compliant"
#pragma warning disable 8603 // Disable "CS8603 Possible null reference return"

namespace Ocelli.OpenClickBank.Builder.Models
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NSwag", "13.19.0.0 (NJsonSchema v10.9.0.0 (Newtonsoft.Json v10.0.0.0))")]
    [Microsoft.AspNetCore.Mvc.Route("rest")]

    public abstract class ShipnoticeControllerBase : Microsoft.AspNetCore.Mvc.ControllerBase
    {
        /// <summary>
        /// Creates a shipping notice for the given transaction.
        /// </summary>
        /// <param name="date">The shipping date (yyyy-mm-dd).</param>
        /// <param name="carrier">The shipping carrier.</param>
        /// <param name="tracking">The tracking id.</param>
        /// <param name="comments">The comments associated with the notice.</param>
        /// <param name="item">The sku/itemNo of the line item. This parameter is required if the transaction includes multiple physical items.</param>
        /// <param name="fillOrder">Indicates that the receipt is part of an order to be shipped altogether, for which the remaining shipping notices should be automatically generated.</param>
        [Microsoft.AspNetCore.Mvc.HttpPost, Microsoft.AspNetCore.Mvc.Route("1.3/shipping3/shipnotice/{receipt}")]
        public abstract System.Threading.Tasks.Task CreateShipnotice([System.ComponentModel.DataAnnotations.Required] Ocelli.OpenClickBank.Builder.Models.CreateShipnoticeRequest request, [Microsoft.AspNetCore.Mvc.FromQuery] string receipt, [Microsoft.AspNetCore.Mvc.FromQuery] string date, [Microsoft.AspNetCore.Mvc.FromQuery] string carrier, [Microsoft.AspNetCore.Mvc.FromQuery] string? tracking = null, [Microsoft.AspNetCore.Mvc.FromQuery] string? comments = null, [Microsoft.AspNetCore.Mvc.FromQuery] string? item = null, [Microsoft.AspNetCore.Mvc.FromQuery] string? fillOrder = null);

        /// <summary>
        /// Returns the ship notices for the given transaction.
        /// </summary>
        [Microsoft.AspNetCore.Mvc.HttpGet, Microsoft.AspNetCore.Mvc.Route("1.3/shipping3/shipnotice/{receipt}")]
        public abstract System.Threading.Tasks.Task GetShipnotice([Microsoft.AspNetCore.Mvc.FromQuery] string receipt);

    }

    


}

#pragma warning restore  108
#pragma warning restore  114
#pragma warning restore  472
#pragma warning restore  612
#pragma warning restore 1573
#pragma warning restore 1591
#pragma warning restore 8073
#pragma warning restore 3016
#pragma warning restore 8603