//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("accountData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("accountData", Namespace="")]
    public partial class AccountData
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("nickName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string NickName { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<QuickstatsData> _quickStats;
        
        [System.Xml.Serialization.XmlElementAttribute("quickStats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Collections.ObjectModel.Collection<QuickstatsData> QuickStats
        {
            get
            {
                return _quickStats;
            }
            set
            {
                _quickStats = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool QuickStatsSpecified
        {
            get
            {
                return ((this.QuickStats != null) 
                            && (this.QuickStats.Count != 0));
            }
        }
    }
}
