//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.864.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.864.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("affiliateTrackingParameters", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AffiliateTrackingParameters
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("offer", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Offer { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("trafficType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafficType { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("trafficSource", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrafficSource { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("campaign", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Campaign { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("adgroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Adgroup { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Ad { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("creative", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Creative { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("extclid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Extclid { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fbclid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Fbclid { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affSub1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffSub1 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affSub2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffSub2 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affSub3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffSub3 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affSub4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffSub4 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affSub5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffSub5 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uniqueAffSub1", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueAffSub1 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uniqueAffSub2", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueAffSub2 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uniqueAffSub3", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueAffSub3 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uniqueAffSub4", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueAffSub4 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("uniqueAffSub5", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UniqueAffSub5 { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("contactId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ContactId { get; set; }
    }
}
