//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contractStatus", Namespace="")]
    public enum ContractStatus
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("PENDING_START")]
        PendingStart,
        
        [System.Xml.Serialization.XmlEnumAttribute("PENDING_APPROVAL")]
        PendingApproval,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACTIVE")]
        Active,
        
        [System.Xml.Serialization.XmlEnumAttribute("TERMINATED")]
        Terminated,
        
        [System.Xml.Serialization.XmlEnumAttribute("TERMINATION_REQUESTED")]
        TerminationRequested,
        
        [System.Xml.Serialization.XmlEnumAttribute("EXPIRED")]
        Expired,
    }
}
