//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.864.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.864.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("contractStatus", Namespace="")]
    public enum ContractStatus
    {
        
        PENDING_START,
        
        PENDING_APPROVAL,
        
        ACTIVE,
        
        TERMINATED,
        
        TERMINATION_REQUESTED,
        
        EXPIRED,
    }
}
