//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("imageData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Image", Namespace="")]
    public partial class ImageData
    {
        
        public virtual bool ShouldSerializeImageid()
        {
            return Imageid.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("imageid", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> Imageid { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title { get; set; }
        
        public virtual bool ShouldSerializeType()
        {
            return Type.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("type", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<ImageType> Type { get; set; }
        
        public virtual bool ShouldSerializeApproved()
        {
            return Approved.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("approved", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> Approved { get; set; }
    }
}
