//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("imageType", Namespace="")]
    public enum ImageType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("PRODUCT")]
        Product,
        
        [System.Xml.Serialization.XmlEnumAttribute("BANNER")]
        Banner,
        
        [System.Xml.Serialization.XmlEnumAttribute("BANNER_CLASSIC")]
        BannerClassic,
        
        [System.Xml.Serialization.XmlEnumAttribute("BANNER_NEW")]
        BannerNew,
        
        [System.Xml.Serialization.XmlEnumAttribute("BANNER_BG")]
        BannerBg,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTOM_BANNER")]
        CustomBanner,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTOM_BANNER_BG")]
        CustomBannerBg,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTOM_ORDERFORM")]
        CustomOrderform,
    }
}
