//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.864.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.864.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("orderData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("orderData", Namespace="")]
    public partial class OrderData
    {
        
        [System.Xml.Serialization.XmlElementAttribute("transactionTime", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> TransactionTime { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receipt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Receipt { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("trackingId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TrackingId { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paytmentMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PaytmentMethod { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("transactionType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string TransactionType { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalOrderAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> TotalOrderAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalShippingAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> TotalShippingAmount { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("totalTaxAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> TotalTaxAmount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("vendor", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Vendor { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affiliate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Affiliate { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("country", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Country { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("state", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string State { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("lastName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string LastName { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("firstName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string FirstName { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("currency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Currency { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("declinedConsent", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<bool> DeclinedConsent { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Email { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("postalCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string PostalCode { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContactField> _customerContactInfo;
        
        [System.Xml.Serialization.XmlElementAttribute("customerContactInfo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Collections.ObjectModel.Collection<ContactField> CustomerContactInfo
        {
            get
            {
                return _customerContactInfo;
            }
            set
            {
                _customerContactInfo = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CustomerContactInfoSpecified
        {
            get
            {
                return ((this.CustomerContactInfo != null) 
                            && (this.CustomerContactInfo.Count != 0));
            }
        }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("role", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string Role { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("fullName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public string FullName { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("customerRefundableState", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<RefundableState> CustomerRefundableState { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<VendorVariableElement> _vendorVariables;
        
        [System.Xml.Serialization.XmlArrayAttribute("vendorVariables", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute("item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Collections.ObjectModel.Collection<VendorVariableElement> VendorVariables
        {
            get
            {
                return _vendorVariables;
            }
            set
            {
                _vendorVariables = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool VendorVariablesSpecified
        {
            get
            {
                return ((this.VendorVariables != null) 
                            && (this.VendorVariables.Count != 0));
            }
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<LineItemData> _lineItemData;
        
        [System.Xml.Serialization.XmlElementAttribute("lineItemData", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<LineItemData> LineItemData
        {
            get
            {
                return _lineItemData;
            }
            set
            {
                _lineItemData = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LineItemDataSpecified
        {
            get
            {
                return ((this.LineItemData != null) 
                            && (this.LineItemData.Count != 0));
            }
        }
    }
}
