//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("price", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("price", Namespace="")]
    public partial class Price
    {
        
        public virtual bool ShouldSerializeNative_Price()
        {
            return Native_Price.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("native_price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Native_Price { get; set; }
        
        public virtual bool ShouldSerializeUsd()
        {
            return Usd.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("usd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Usd { get; set; }
        
        public virtual bool ShouldSerializeUsd_With_Fees()
        {
            return Usd_With_Fees.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("usd_with_fees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Usd_With_Fees { get; set; }
    }
}
