//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("price", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("price", Namespace="")]
    public partial class Price
    {
        
        public virtual bool ShouldSerializeNativePrice()
        {
            return NativePrice.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("native_price", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> NativePrice { get; set; }
        
        public virtual bool ShouldSerializeUsd()
        {
            return Usd.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("usd", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Usd { get; set; }
        
        public virtual bool ShouldSerializeUsdWithFees()
        {
            return UsdWithFees.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("usd_with_fees", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> UsdWithFees { get; set; }
    }
}
