//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("productData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Product", Namespace="")]
    public partial class ProductData
    {
        
        public virtual bool ShouldSerializeId()
        {
            return Id.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> Id { get; set; }
        
        public virtual bool ShouldSerializeStatus()
        {
            return Status.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<ActiveStatus> Status { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("digital", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Digital { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("physical", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Physical { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("digitalRecurring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool DigitalRecurring { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("physicalRecurring", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PhysicalRecurring { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("site", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Site { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("created", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Created { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("updated", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Updated { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("approval_status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ProductApprovalStatus ApprovalStatus { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("language", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Language { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("post_purchase_description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PostPurchaseDescription { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("image", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ImageBean Image { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("thank_you_pages")]
        public ThankYouPages ThankYouPages { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pitch_pages")]
        public PitchPages PitchPages { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("commission")]
        public ProductCommission Commission { get; set; }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Pricing> _pricings;
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("pricings", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("pricing")]
        public System.Collections.ObjectModel.Collection<Pricing> Pricings
        {
            get
            {
                return _pricings;
            }
            set
            {
                _pricings = value;
            }
        }
        
        public virtual bool ShouldSerializePricings()
        {
            return ((this.Pricings != null) 
                        && (this.Pricings.Count != 0));
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ContractBean> _contracts;
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlArrayAttribute("contracts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("contract", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ContractBean> Contracts
        {
            get
            {
                return _contracts;
            }
            set
            {
                _contracts = value;
            }
        }
        
        public virtual bool ShouldSerializeContracts()
        {
            return ((this.Contracts != null) 
                        && (this.Contracts.Count != 0));
        }
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ProductCategory> _categories;
        
        [System.Xml.Serialization.XmlArrayAttribute("categories", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("category", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<ProductCategory> Categories
        {
            get
            {
                return _categories;
            }
            set
            {
                _categories = value;
            }
        }
        
        public virtual bool ShouldSerializeCategories()
        {
            return ((this.Categories != null) 
                        && (this.Categories.Count != 0));
        }
        
        public virtual bool ShouldSerializeDisableGeoCurrency()
        {
            return DisableGeoCurrency.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("disable_geo_currency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> DisableGeoCurrency { get; set; }
        
        public virtual bool ShouldSerializeAllowCurrencyChange()
        {
            return AllowCurrencyChange.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("allow_currency_change", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> AllowCurrencyChange { get; set; }
        
        public virtual bool ShouldSerializeUsTaxExempt()
        {
            return UsTaxExempt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("us_tax_exempt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> UsTaxExempt { get; set; }
        
        public virtual bool ShouldSerializeRevenueRecognition()
        {
            return RevenueRecognition.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("revenue_recognition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<RevRec> RevenueRecognition { get; set; }
        
        public virtual bool ShouldSerializeReducedUpsellMarkup()
        {
            return ReducedUpsellMarkup.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("reduced_upsell_markup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> ReducedUpsellMarkup { get; set; }
        
        public virtual bool ShouldSerializeSkipConfirmationPage()
        {
            return SkipConfirmationPage.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("skip_confirmation_page", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> SkipConfirmationPage { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("admin_download_url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AdminDownloadUrl { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("admin_mobile_download_url", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AdminMobileDownloadUrl { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("no_commission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool NoCommission { get; set; }
        
        public virtual bool ShouldSerializeSaleRefundDaysLimit()
        {
            return SaleRefundDaysLimit.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("sale_refund_days_limit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> SaleRefundDaysLimit { get; set; }
        
        public virtual bool ShouldSerializeRebillRefundDaysLimit()
        {
            return RebillRefundDaysLimit.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("rebill_refund_days_limit", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> RebillRefundDaysLimit { get; set; }
        
        public virtual bool ShouldSerializeAdminRestrictFlexibleRefund()
        {
            return AdminRestrictFlexibleRefund.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("admin_restrict_flexible_refund", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<bool> AdminRestrictFlexibleRefund { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("commission_tier_override", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool CommissionTierOverride { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("deliveryMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliveryMethod { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("deliverySpeed", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string DeliverySpeed { get; set; }
        
        public virtual bool ShouldSerializeMaxQuantity()
        {
            return MaxQuantity.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("maxQuantity", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> MaxQuantity { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("isPartOfOrderBump", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsPartOfOrderBump { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("isInitialOfOrderBump", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsInitialOfOrderBump { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute(AllowEmptyStrings=true)]
        [System.Xml.Serialization.XmlElementAttribute("isProductOfOrderBump", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool IsProductOfOrderBump { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlAttributeAttribute("sku")]
        public string Sku { get; set; }
    }
}
