//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("productCategory", Namespace="")]
    public enum ProductCategory
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("EBOOK")]
        Ebook,
        
        [System.Xml.Serialization.XmlEnumAttribute("SOFTWARE")]
        Software,
        
        [System.Xml.Serialization.XmlEnumAttribute("GAMES")]
        Games,
        
        [System.Xml.Serialization.XmlEnumAttribute("AUDIO")]
        Audio,
        
        [System.Xml.Serialization.XmlEnumAttribute("VIDEO")]
        Video,
        
        [System.Xml.Serialization.XmlEnumAttribute("MEMBER_SITE")]
        MemberSite,
    }
}
