//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("productCommission", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("commission", Namespace="")]
    public partial class ProductCommission
    {
        
        public virtual bool ShouldSerializePurchase()
        {
            return Purchase.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("purchase", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Purchase { get; set; }
        
        public virtual bool ShouldSerializeRebill()
        {
            return Rebill.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("rebill", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> Rebill { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("no_rebill_commission", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool No_Rebill_Commission { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("commission_tier_override", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Commission_Tier_Override { get; set; }
    }
}
