//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("recurringFrequency", Namespace="")]
    public enum RecurringFrequency
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("WEEKLY")]
        Weekly,
        
        [System.Xml.Serialization.XmlEnumAttribute("BI_WEEKLY")]
        BiWeekly,
        
        [System.Xml.Serialization.XmlEnumAttribute("MONTHLY")]
        Monthly,
        
        [System.Xml.Serialization.XmlEnumAttribute("QUARTERLY")]
        Quarterly,
        
        [System.Xml.Serialization.XmlEnumAttribute("HALF_YEARLY")]
        HalfYearly,
        
        [System.Xml.Serialization.XmlEnumAttribute("YEARLY")]
        Yearly,
        
        [System.Xml.Serialization.XmlEnumAttribute("MONTHS")]
        Months,
        
        [System.Xml.Serialization.XmlEnumAttribute("WEEKS")]
        Weeks,
        
        [System.Xml.Serialization.XmlEnumAttribute("DAYS")]
        Days,
    }
}
