//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("refundableState", Namespace="")]
    public enum RefundableState
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("REFUNDABLE")]
        Refundable,
        
        [System.Xml.Serialization.XmlEnumAttribute("SUGGESTED_REFUND_BLOCK")]
        SuggestedRefundBlock,
        
        [System.Xml.Serialization.XmlEnumAttribute("UNREFUNDABLE")]
        Unrefundable,
        
        [System.Xml.Serialization.XmlEnumAttribute("ALREADY_REFUNDED")]
        AlreadyRefunded,
        
        [System.Xml.Serialization.XmlEnumAttribute("TOO_OLD")]
        TooOld,
        
        [System.Xml.Serialization.XmlEnumAttribute("REFUND_BLOCKED")]
        RefundBlocked,
        
        [System.Xml.Serialization.XmlEnumAttribute("HAS_OPEN_REFUND")]
        HasOpenRefund,
        
        [System.Xml.Serialization.XmlEnumAttribute("OVER_ELV_LIMIT")]
        OverElvLimit,
        
        [System.Xml.Serialization.XmlEnumAttribute("PROVIDER_DISCONNECTED")]
        ProviderDisconnected,
    }
}
