//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("refundType", Namespace="")]
    public enum RefundType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("FULL")]
        Full,
        
        [System.Xml.Serialization.XmlEnumAttribute("PARTIAL_PERCENT")]
        PartialPercent,
        
        [System.Xml.Serialization.XmlEnumAttribute("PARTIAL_AMOUNT")]
        PartialAmount,
        
        [System.Xml.Serialization.XmlEnumAttribute("PARTIAL_QUANTITY")]
        PartialQuantity,
        
        [System.Xml.Serialization.XmlEnumAttribute("TAX")]
        Tax,
    }
}
