//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("revRec", Namespace="")]
    public enum RevRec
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("LD")]
        Ld,
        
        [System.Xml.Serialization.XmlEnumAttribute("VD")]
        Vd,
        
        [System.Xml.Serialization.XmlEnumAttribute("LM")]
        Lm,
        
        [System.Xml.Serialization.XmlEnumAttribute("LMA")]
        Lma,
        
        [System.Xml.Serialization.XmlEnumAttribute("LMID")]
        Lmid,
        
        [System.Xml.Serialization.XmlEnumAttribute("VM")]
        Vm,
        
        I,
    }
}
