//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("role", Namespace="")]
    public enum Role
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("VENDOR")]
        Vendor,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTOMER")]
        Customer,
        
        [System.Xml.Serialization.XmlEnumAttribute("CBCSR")]
        Cbcsr,
        
        [System.Xml.Serialization.XmlEnumAttribute("CBSYSTEM")]
        Cbsystem,
        
        [System.Xml.Serialization.XmlEnumAttribute("USER")]
        User,
    }
}
