//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("status", Namespace="")]
    public enum Status
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("OPEN")]
        Open,
        
        [System.Xml.Serialization.XmlEnumAttribute("REOPENED")]
        Reopened,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLOSED")]
        Closed,
    }
}
