//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketSource", Namespace="")]
    public enum TicketSource
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("API")]
        Api,
        
        [System.Xml.Serialization.XmlEnumAttribute("CUSTOMER_WAM")]
        CustomerWam,
        
        [System.Xml.Serialization.XmlEnumAttribute("UNKNOWN")]
        Unknown,
        
        [System.Xml.Serialization.XmlEnumAttribute("RNFDS_EMAIL")]
        RnfdsEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("CNCLS_EMAIL")]
        CnclsEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("VENDOR_WAM")]
        VendorWam,
        
        [System.Xml.Serialization.XmlEnumAttribute("VENDOR_ADMIN")]
        VendorAdmin,
        
        [System.Xml.Serialization.XmlEnumAttribute("CSR_ADMIN")]
        CsrAdmin,
        
        [System.Xml.Serialization.XmlEnumAttribute("SECURITY")]
        Security,
        
        [System.Xml.Serialization.XmlEnumAttribute("CSR_WAM")]
        CsrWam,
        
        [System.Xml.Serialization.XmlEnumAttribute("CONVERSION_PROCESS")]
        ConversionProcess,
        
        [System.Xml.Serialization.XmlEnumAttribute("BUSINESS_DEVELOPMENT_FORM")]
        BusinessDevelopmentForm,
        
        [System.Xml.Serialization.XmlEnumAttribute("COMMUNICATIONS_EMAIL")]
        CommunicationsEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACCOUNTS_EMAIL")]
        AccountsEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("CBCS_EMAIL")]
        CbcsEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACCOUNTING_EMAIL")]
        AccountingEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("WAM_ACCT_QUESTION")]
        WamAcctQuestion,
        
        [System.Xml.Serialization.XmlEnumAttribute("WAM_WIREGROUP_DETAIL")]
        WamWiregroupDetail,
        
        [System.Xml.Serialization.XmlEnumAttribute("MARKETING_EMAIL")]
        MarketingEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("PAYMENTECH_BATCH")]
        PaymentechBatch,
        
        [System.Xml.Serialization.XmlEnumAttribute("PYPL_JPY_CANCELLER")]
        PyplJpyCanceller,
        
        [System.Xml.Serialization.XmlEnumAttribute("ECUSTOMS")]
        Ecustoms,
        
        [System.Xml.Serialization.XmlEnumAttribute("LASHBACK")]
        Lashback,
        
        [System.Xml.Serialization.XmlEnumAttribute("SPAM_EMAIL")]
        SpamEmail,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLICKBANK_DATABASE_SCRIPT")]
        ClickbankDatabaseScript,
        
        [System.Xml.Serialization.XmlEnumAttribute("API_VIRTUAL_SOURCE")]
        ApiVirtualSource,
        
        [System.Xml.Serialization.XmlEnumAttribute("KOUNT")]
        Kount,
        
        [System.Xml.Serialization.XmlEnumAttribute("PAYPAL_ADAPTIVE")]
        PaypalAdaptive,
        
        [System.Xml.Serialization.XmlEnumAttribute("CB_POWERED_PROGRAM")]
        CbPoweredProgram,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLKBANK")]
        Clkbank,
    }
}
