//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketActionType", Namespace="")]
    public enum TicketActionType
    {
        
        ASSIGNED,
        
        COMMENTED,
        
        CHANGED,
        
        CLOSED,
        
        EXPIRED,
        
        REOPENED,
        
        OPENED,
        
        APPROVED,
        
        DISAPPROVED,
        
        ATTACHMENT,
        
        ADMIN_CHANGE,
        
        REFUND_ACKED,
        
        NEW_PHOTO_ID,
    }
}
