//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketType", Namespace="")]
    public enum TicketType
    {
        
        TECH_SUPPORT,
        
        REFUND,
        
        CANCEL,
        
        PRODUCT_CHANGE,
        
        ORDER_LOOKUP,
        
        ESCALATED,
        
        APPROVAL_IMAGE,
        
        APPROVAL_UPSELL,
        
        APPROVAL_CATEGORY_CHANGE,
        
        APPROVAL_PRODUCT,
        
        APPROVAL_ADVANCED_UPSELL,
        
        APPROVAL_CSS_ORDERFORM,
        
        APPROVAL_TEMPLATE_ORDERFORM,
        
        APPROVAL_ORDER_BUMP_CUSTOM_TEXT,
        
        APPROVAL_EXIT_OFFER,
        
        APPROVAL_PHOTO_ID,
        
        ACCT_QUESTION_ACCOUNTS,
        
        ACCT_QUESTION_ACCOUNTING,
        
        SPAM,
        
        ACCOUNT_ABUSE,
        
        SECURITY_CONCERN,
    }
}
