//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketSource", Namespace="")]
    public enum TicketSource
    {
        
        API,
        
        CUSTOMER_WAM,
        
        UNKNOWN,
        
        RNFDS_EMAIL,
        
        CNCLS_EMAIL,
        
        VENDOR_WAM,
        
        VENDOR_ADMIN,
        
        CSR_ADMIN,
        
        SECURITY,
        
        CSR_WAM,
        
        CONVERSION_PROCESS,
        
        BUSINESS_DEVELOPMENT_FORM,
        
        COMMUNICATIONS_EMAIL,
        
        ACCOUNTS_EMAIL,
        
        CBCS_EMAIL,
        
        ACCOUNTING_EMAIL,
        
        WAM_ACCT_QUESTION,
        
        WAM_WIREGROUP_DETAIL,
        
        MARKETING_EMAIL,
        
        PAYMENTECH_BATCH,
        
        PYPL_JPY_CANCELLER,
        
        ECUSTOMS,
        
        LASHBACK,
        
        SPAM_EMAIL,
        
        CLICKBANK_DATABASE_SCRIPT,
        
        API_VIRTUAL_SOURCE,
        
        KOUNT,
        
        PAYPAL_ADAPTIVE,
        
        CB_POWERED_PROGRAM,
        
        CLKBANK,
    }
}
