//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketType", Namespace="")]
    public enum TicketType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("TECH_SUPPORT")]
        TechSupport,
        
        [System.Xml.Serialization.XmlEnumAttribute("REFUND")]
        Refund,
        
        [System.Xml.Serialization.XmlEnumAttribute("CANCEL")]
        Cancel,
        
        [System.Xml.Serialization.XmlEnumAttribute("PRODUCT_CHANGE")]
        ProductChange,
        
        [System.Xml.Serialization.XmlEnumAttribute("ORDER_LOOKUP")]
        OrderLookup,
        
        [System.Xml.Serialization.XmlEnumAttribute("ESCALATED")]
        Escalated,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_IMAGE")]
        ApprovalImage,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_UPSELL")]
        ApprovalUpsell,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_CATEGORY_CHANGE")]
        ApprovalCategoryChange,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_PRODUCT")]
        ApprovalProduct,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_FUNNEL")]
        ApprovalFunnel,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_PRODUCT_V2")]
        ApprovalProductV2,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_ADVANCED_UPSELL")]
        ApprovalAdvancedUpsell,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_TEMPLATE_ORDERFORM")]
        ApprovalTemplateOrderform,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_TEMPLATE_EXITOFFER")]
        ApprovalTemplateExitoffer,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_ORDER_BUMP_CUSTOM_TEXT")]
        ApprovalOrderBumpCustomText,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVAL_PHOTO_ID")]
        ApprovalPhotoId,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACCT_QUESTION_ACCOUNTS")]
        AcctQuestionAccounts,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACCT_QUESTION_ACCOUNTING")]
        AcctQuestionAccounting,
        
        [System.Xml.Serialization.XmlEnumAttribute("SPAM")]
        Spam,
        
        [System.Xml.Serialization.XmlEnumAttribute("ACCOUNT_ABUSE")]
        AccountAbuse,
        
        [System.Xml.Serialization.XmlEnumAttribute("SECURITY_CONCERN")]
        SecurityConcern,
    }
}
