//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.1.1179.0
namespace v1_3.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.1.1179.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ticketActionType", Namespace="")]
    public enum TicketActionType
    {
        
        [System.Xml.Serialization.XmlEnumAttribute("ASSIGNED")]
        Assigned,
        
        [System.Xml.Serialization.XmlEnumAttribute("COMMENTED")]
        Commented,
        
        [System.Xml.Serialization.XmlEnumAttribute("CHANGED")]
        Changed,
        
        [System.Xml.Serialization.XmlEnumAttribute("CLOSED")]
        Closed,
        
        [System.Xml.Serialization.XmlEnumAttribute("EXPIRED")]
        Expired,
        
        [System.Xml.Serialization.XmlEnumAttribute("REOPENED")]
        Reopened,
        
        [System.Xml.Serialization.XmlEnumAttribute("OPENED")]
        Opened,
        
        [System.Xml.Serialization.XmlEnumAttribute("APPROVED")]
        Approved,
        
        [System.Xml.Serialization.XmlEnumAttribute("DISAPPROVED")]
        Disapproved,
        
        [System.Xml.Serialization.XmlEnumAttribute("ATTACHMENT")]
        Attachment,
        
        [System.Xml.Serialization.XmlEnumAttribute("ADMIN_CHANGE")]
        AdminChange,
        
        [System.Xml.Serialization.XmlEnumAttribute("REFUND_ACKED")]
        RefundAcked,
        
        [System.Xml.Serialization.XmlEnumAttribute("NEW_PHOTO_ID")]
        NewPhotoId,
    }
}
