//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("partialRefundData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("partialRefundData", Namespace="")]
    public partial class PartialRefundData
    {
        
        public virtual bool ShouldSerializeUsdAmount()
        {
            return UsdAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("usdAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> UsdAmount { get; set; }
        
        public virtual bool ShouldSerializeCustomerAmount()
        {
            return CustomerAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("customerAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> CustomerAmount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerCurrency { get; set; }
        
        public virtual bool ShouldSerializeProductAmount()
        {
            return ProductAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("productAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> ProductAmount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("productCurrency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ProductCurrency { get; set; }
    }
}
