//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("productApprovalStatus", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("product_approval_status", Namespace="")]
    public partial class ProductApprovalStatus
    {
        
        public virtual bool ShouldSerializeTicket_Id()
        {
            return Ticket_Id.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("ticket_id", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<int> Ticket_Id { get; set; }
        
        public virtual bool ShouldSerializeStatus()
        {
            return Status.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<Status> Status { get; set; }
        
        public virtual bool ShouldSerializeLast_Action_Performed_By()
        {
            return Last_Action_Performed_By.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("last_action_performed_by", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<Role> Last_Action_Performed_By { get; set; }
    }
}
