//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("refundableState", Namespace="")]
    public enum RefundableState
    {
        
        REFUNDABLE,
        
        SUGGESTED_REFUND_BLOCK,
        
        UNREFUNDABLE,
        
        ALREADY_REFUNDED,
        
        TOO_OLD,
        
        REFUND_BLOCKED,
        
        HAS_OPEN_REFUND,
        
        OVER_ELV_LIMIT,
        
        PROVIDER_DISCONNECTED,
    }
}
