//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("subscriptionProductRowData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscriptionProductRowData
    {
        
        public virtual bool ShouldSerializeAvgActiveSubCnt()
        {
            return AvgActiveSubCnt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("avgActiveSubCnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> AvgActiveSubCnt { get; set; }
        
        public virtual bool ShouldSerializeAvgSubAge()
        {
            return AvgSubAge.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("avgSubAge", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> AvgSubAge { get; set; }
        
        public virtual bool ShouldSerializeAvgSubValue()
        {
            return AvgSubValue.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("avgSubValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> AvgSubValue { get; set; }
        
        public virtual bool ShouldSerializeBusinessDate()
        {
            return BusinessDate.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("businessDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.Nullable<System.DateTime> BusinessDate { get; set; }
        
        public virtual bool ShouldSerializeCancelSubCnt()
        {
            return CancelSubCnt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("cancelSubCnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> CancelSubCnt { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("description", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Description { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("duration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Duration { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("frequency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Frequency { get; set; }
        
        public virtual bool ShouldSerializeGrossSales()
        {
            return GrossSales.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("grossSales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> GrossSales { get; set; }
        
        public virtual bool ShouldSerializeInitialSaleAmt()
        {
            return InitialSaleAmt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("initialSaleAmt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> InitialSaleAmt { get; set; }
        
        public virtual bool ShouldSerializeInitialSaleCnt()
        {
            return InitialSaleCnt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("initialSaleCnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> InitialSaleCnt { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNo { get; set; }
        
        public virtual bool ShouldSerializeNetSales()
        {
            return NetSales.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("netSales", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> NetSales { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("nickname", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Nickname { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("productId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ProductId { get; set; }
        
        public virtual bool ShouldSerializeRecurringSaleAmt()
        {
            return RecurringSaleAmt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("recurringSaleAmt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> RecurringSaleAmt { get; set; }
        
        public virtual bool ShouldSerializeRecurringSaleCnt()
        {
            return RecurringSaleCnt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("recurringSaleCnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> RecurringSaleCnt { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("title", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Title { get; set; }
        
        public virtual bool ShouldSerializeTotalSalesCnt()
        {
            return TotalSalesCnt.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("totalSalesCnt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> TotalSalesCnt { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("trialPeriod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrialPeriod { get; set; }
    }
}
