//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("subscriptionDetailsRowData", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscriptionDetailsRowData
    {
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("affNickName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AffNickName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("cancelled", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Cancelled { get; set; }
        
        public virtual bool ShouldSerializeChargebackAmount()
        {
            return ChargebackAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("chargebackAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> ChargebackAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("chargebackCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ChargebackCount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("countryCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CountryCode { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("currencyCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CurrencyCode { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerDisplayName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerDisplayName { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerFirstName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerFirstName { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("customerLastName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CustomerLastName { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("duration", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int Duration { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("email", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Email { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("frequency", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Frequency { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("ftxnId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int FtxnId { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("futurePaymentsCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int FuturePaymentsCount { get; set; }
        
        public virtual bool ShouldSerializeInitialSaleAmount()
        {
            return InitialSaleAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("initialSaleAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> InitialSaleAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("initialSaleCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int InitialSaleCount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("itemNo", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string ItemNo { get; set; }
        
        [System.Xml.Serialization.XmlElementAttribute("nextPaymentDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, DataType="dateTime")]
        public System.Nullable<System.DateTime> NextPaymentDate { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("paymentMethod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PaymentMethod { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("processedPaymentsCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int ProcessedPaymentsCount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("province", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Province { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("pubNickName", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PubNickName { get; set; }
        
        public virtual bool ShouldSerializePurchaseDate()
        {
            return PurchaseDate.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("purchaseDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.Nullable<System.DateTime> PurchaseDate { get; set; }
        
        public virtual bool ShouldSerializeRebillSaleAmount()
        {
            return RebillSaleAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("rebillSaleAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> RebillSaleAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("rebillSaleCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RebillSaleCount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("receipt", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Receipt { get; set; }
        
        public virtual bool ShouldSerializeRefundAmount()
        {
            return RefundAmount.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("refundAmount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> RefundAmount { get; set; }
        
        [System.ComponentModel.DataAnnotations.RequiredAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("refundCount", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int RefundCount { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("status", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Status { get; set; }
        
        public virtual bool ShouldSerializeSubCancelDate()
        {
            return SubCancelDate.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("subCancelDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.Nullable<System.DateTime> SubCancelDate { get; set; }
        
        public virtual bool ShouldSerializeSubEndDate()
        {
            return SubEndDate.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("subEndDate", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="dateTime")]
        public System.Nullable<System.DateTime> SubEndDate { get; set; }
        
        public virtual bool ShouldSerializeSubValue()
        {
            return SubValue.HasValue;
        }
        
        [System.Xml.Serialization.XmlElementAttribute("subValue", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Nullable<decimal> SubValue { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("timeStr", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TimeStr { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("trialPeriod", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TrialPeriod { get; set; }
        
        [System.Diagnostics.CodeAnalysis.AllowNullAttribute()]
        [System.Diagnostics.CodeAnalysis.MaybeNullAttribute()]
        [System.Xml.Serialization.XmlElementAttribute("txnType", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TxnType { get; set; }
    }
}
