//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.719.0
namespace Ocelli.OpenClickBank.Shared.Models
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.719.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("subscriptionDetailsDataWrapper", Namespace="")]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SubscriptionDetailsDataWrapper
    {
        
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<SubscriptionDetailsRowData> _row;
        
        [System.Xml.Serialization.XmlElementAttribute("row", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.Collections.ObjectModel.Collection<SubscriptionDetailsRowData> Row
        {
            get
            {
                return _row;
            }
            set
            {
                _row = value;
            }
        }
        
        /// <summary>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RowSpecified
        {
            get
            {
                return ((this.Row != null) 
                            && (this.Row.Count != 0));
            }
        }
    }
}
