name: "Deploy to NuGet"

on:
  push:
    tags:
      - 'v[0-9]+.*'

env:
  PROJECT_PATH: "src/Ocelli.OpenClickBank/Ocelli.OpenClickBank.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"

jobs:
  deploy:
    name: "Deploy"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Install dotnet"
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.0.x"

      - name: "Restore packages"
        run: dotnet restore

      - name: "Write testing api keys to file"
        run: 'echo "$CLICKBANK_API_KEY" > tests/Ocelli.OpenClickBank.Tests/api_key.json'
        shell: bash
        env:
          CLICKBANK_API_KEY: ${{secrets.CLICKBANK_API_KEY}}

      - name: "Build projects"
        run: dotnet build --no-restore --configuration Release

      #- name: "Test project"
      #  run: dotnet test --no-build --verbosity normal --configuration Release
      #  env:
      #    CLICKBANK_API_KEY: ${{secrets.CLICKBANK_API_KEY}}

      - name: "Get Version"
        id: version
        uses: battila7/get-version-action@v2

      - name: "Pack project"
        run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ steps.version.outputs.version-without-v }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

      - name: "Push package"
        run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ secrets.NUGET_API_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
